FROM node:18.20-alpine

# set working dir
WORKDIR /app

# copy package.json to app
COPY package.json /app/

# install dependency
RUN rm -rf node_modules && npm install

# copy code to app
COPY  ./ /app/

# expose port
EXPOSE 5173

# start the app
CMD ["npm", "run", "dev", "--", "--host"]

