import { youthType } from "../../types";
import { sabhaType } from "../../types";
import youthImageSrc from "../assets/profilePicture.png";
export const youthdata: youthType[] = [
  {
    youthId: 1,
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
    birthdate: new Date("2025-04-09"),
    cityInGermany: "Berlin",
    cityInIndia: "Mumbai",
    phoneNumber: "+491234567890",
    whatsAppNumber: "+491234567890",
    educationInGermany: "Computer Science",
    refNameforSabha: "Mr. Smith",
    sabhaType: "Thursday",
    youthImage: youthImageSrc,
    whatsAppNumberCountry: "",
  },
  {
    youthId: 2,
    email: "jane.smith@example.com",
    firstName: "Jane",
    lastName: "Smith",
    birthdate: new Date("2023-12-15"),
    cityInGermany: "Hamburg",
    cityInIndia: "Delhi",
    phoneNumber: "+4911122233344",
    whatsAppNumber: "+4911122233344",
    educationInGermany: "Business Administration",
    refNameforSabha: "Mrs. Johnson",
    sabhaType: "Cultural Sabha",
    youthImage: youthImageSrc,
    whatsAppNumberCountry: "",
  },
  {
    youthId: 3,
    email: "alice.davis@example.com",
    firstName: "Alice",
    lastName: "Davis",
    birthdate: new Date("1992-11-07"),
    cityInGermany: "Munich",
    cityInIndia: "Bangalore",
    phoneNumber: "+498765432109",
    whatsAppNumber: "+498765432109",
    educationInGermany: "Mechanical Engineering",
    refNameforSabha: "Mr. Patel",
    sabhaType: "Social Sabha",
    youthImage: youthImageSrc,
    whatsAppNumberCountry: "",
  },
  {
    youthId: 4,
    email: "robert.jones@example.com",
    firstName: "Robert",
    lastName: "Jones",
    birthdate: new Date("1988-03-25"),
    cityInGermany: "Frankfurt",
    cityInIndia: "Chennai",
    phoneNumber: "+497654321098",
    whatsAppNumber: "+497654321098",
    educationInGermany: "Electrical Engineering",
    refNameforSabha: "Mr. Kumar",
    sabhaType: "Youth Sabha",
    youthImage: youthImageSrc,
    whatsAppNumberCountry: "",
  },
  {
    youthId: 5,
    email: "emma.white@example.com",
    firstName: "Emma",
    lastName: "White",
    birthdate: new Date("1995-06-18"),
    cityInGermany: "Stuttgart",
    cityInIndia: "Hyderabad",
    phoneNumber: "+499876543210",
    whatsAppNumber: "+499876543210",
    educationInGermany: "Psychology",
    refNameforSabha: "Mr. Gupta",
    sabhaType: "Sports Sabha",
    youthImage: youthImageSrc,
    whatsAppNumberCountry: "",
  },
];

export const sabhaData: sabhaType[] = [
  {
    title: "Gujarati Sabha",
    date: new Date("2025-06-14"),
    topic: "Aapda keva Samart Mavtar",
    speaker: {
      speakerOne: "Muster man",
      speakerTwo: "Muster Frau",
    },
  },
  {
    title: "General Sabha",
    date: new Date("2025-06-15"),
    topic: "A Saint – A Never Failing Compass",
    speaker: {
      speakerOne: "Muster man",
      speakerTwo: "Muster Frau",
    },
  },
];
